### ISSUE TITLE
Alt text value not applied to aria-label

### ISSUE THREAD

**Issue by RMurray89** [cgkineo/adapt-homeButton#10]
Hi,

It appears the alt attribute is not applied to the aria-label for this component. It is announced simply as a link by the screen reader.

Thanks
Ross

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-homeButton/blob/master/js/adapt-homeButton.js#L52 It should be working just fine?
https://github.com/cgkineo/adapt-homeButton/blob/master/js/adapt-homeButton.js#L25

**Comment by oliverfoster** [comment]
the alt config was coming from the wrong place.
