### ISSUE TITLE
Add support for Tooltip API and Navigation Button API

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-homeButton#16]
For consistency with other navigation buttons when tooltips are enabled, homeButton should support the Core tooltip API https://github.com/adaptlearning/adapt-contrib-core/pull/207

Note, this might require a slightly different implementation as the button can be redirected so would need to support the use case for the tooltip text to be overwritten where applicable. Example, redirecting the home button to a start page. 

My initial suggestion is to keep the standard home button tooltip config as per the existing tooltip functionality - we can assume the default will be 'home' (menu). With the addition to overwrite 'tooltip' within the [_homeButton config](https://github.com/cgkineo/adapt-homeButton/blob/172a9a90ffa043acf2f7b63c81212dff65f75992/example.json#L18). I'd be keen to get input or suggestions on this?

**Comment by swashbuck** [comment]
Added Navigation Button API to the ticket title. I'll do these both at the same time.
