### ISSUE TITLE
No option to change default icons

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-homeButton#19]
Currently, there is no option to change the home or the back button icon.

**Comment by swashbuck** [comment]
@StuartNicholls What do you propose? Some thoughts:

- We could align this with Page Nav and use `_iconClass` ( https://github.com/cgkineo/adapt-pageNav/blob/0eb5467f5d8dfaa72af94e1f0549e02dbb2a0fdc/example.json#L40 )?
- Default to 'icon-home'
- Have the ability to override at the course or content object level
- Should an icon class be explicitly _required_ or could it fall back to 'icon-home' if the user leaves the field blank?
- Ideally, the default would be based on `_hideHomeButton` and `_hideBackButton`, but I don't believe that's currently possible.

I would suggest that we do this once #27 is approved and merged. I'm currently working on this.

**Comment by kirsty-hames** [comment]
All sounds good to me @swashbuck.

> * Should an icon class be explicitly _required_ or could it fall back to 'icon-home' if the user leaves the field blank?

Seeing as Adapt navigation buttons are icon buttons as standard, I'd keep 'icon-home' as the fall back.
