### ISSUE TITLE
Template should exist for this component

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-homeButton#23]
### Subject of the issue/enhancement/features
Instead of the HTML being generated in the JS, there should instead by a JSX (preferably) or HBS template. Nothing is broken but instead recommended global common practices for ease of editing later.

**Comment by swashbuck** [comment]
This will be included in #24

**Comment by oliverfoster** [comment]
Closed in https://github.com/cgkineo/adapt-homeButton/commit/04fbc9e9e6299f214fa07b6197e3019a0b237656
