### ISSUE TITLE
Appears to be breaking access to the Project Settings page

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-homeButton#26]
### Subject of the issue/enhancement/features
Without the plugin within the course the Project settings page can be accessed, when v1.1.0 of the plugin is added, the Project settings page displays no content.

### Your environment
* version (AT v0.11.1/Framework v5.31.22)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Add the Home Button plugin

### Expected behaviour
To be able to access the Project setting page

### Actual behaviour
Can click the Project settings page link, but nothing is displayed

### Screenshots (if you can)
![2023-08-16_11-14-21](https://github.com/cgkineo/adapt-homeButton/assets/29701150/f86e8359-49e2-40a6-8f9c-b32f14f2ac53)

**Comment by swashbuck** [comment]
@fosterc1 There is a known issue where the schemas need to be updated #25 . Are you able to use an older version of the plugin until that's fixed (hopefully by this week or next at the latest)?

**Comment by swashbuck** [comment]
Also, this now requires Framework version 5.30.3 or higher. This will be updated in the readme.

**Comment by swashbuck** [comment]
@fosterc1 PR is ready for review. Should fix the schema issues.

https://github.com/cgkineo/adapt-homeButton/pull/27

Let me know if we can close this ticket. Thanks.

**Comment by fosterc1** [comment]
Not sure how I review this tbh, do you have a link to the updated zip file to upload the plugin?

**Comment by swashbuck** [comment]
@fosterc1 This was actually just merged into master, so you can update with the latest release (v1.1.1).

**Comment by fosterc1** [comment]
Hello

@swashbuck v1.1.1 is still breaking the Project settings page.

Thanks

**Comment by swashbuck** [comment]
@fosterc1 What version of the Vanilla theme are you using?

**Comment by fosterc1** [comment]
@swashbuck v9.8.3

**Comment by swashbuck** [comment]
Thanks, @fosterc1 . Can you click in Configuration settings? Are you seeing any console errors in the browser?

**Comment by fosterc1** [comment]
Hello @swashbuck 

This is definately an issue in the plugin, as I've created a fresh environment with a new course. All is working well until v1.1.1 of the Home plugin is installed.

Command failed: npx grunt server-build:prod --outputdir=courses/64e89acc247fae32da097501/64e89c616a106533e1567d91/build --theme=64e89b1a247fae32da097595 --menu=adapt-contrib-boxMenu
Plugin folder name 64e89b1a247fae32da097595 does not match package name adapt-contrib-vanilla.

Hope this helps

**Comment by swashbuck** [comment]
Thanks, @fosterc1 

I don't suppose you have access to an AAT **v0.10.5** testing environment? Home Button was working in one of our v0.10.5 sandbox sites.

Regardless, we will keep looking into this.

**Comment by swashbuck** [comment]
^^ Nevermind about the AAT version. We've managed to break it in v0.10.5, too.

**Comment by swashbuck** [comment]
@taylortom Would you be able to take a look at this? I'm not sure where we left off, but I know there was an AAT patch floating around somewhere. Would the patch fix this issue?

Note that I do have PR #29 started for this.

**Comment by swashbuck** [comment]
@taylortom Do you think v0.11.2 of `adapt_authoring` would fix this issue?

https://github.com/adaptlearning/adapt_authoring/blob/master/CHANGELOG.md#0112---2023-09-25

**Comment by swashbuck** [comment]
@fosterc1 Are you able to reproduce the issue in AAT v0.11.2 and using the PR #29 ? We think this combination will fix the issue.
