### ISSUE TITLE
Rename to adapt-kineo-homeButton?

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-homeButton#28]
### Subject of the issue
Should we rename this plugin to `adapt-kineo-homeButton`? This is a **public** plugin so renaming would clearly identify Kineo as the vendor.

**Comment by kirsty-hames** [comment]
I think any public Kineo plugin that is accessible, supports RTL and AAT compatible should have the Kineo name to show it's a plugin we'll continue to maintain. It will also avoid duplication if another vendor develops a plugin under the same name.

In terms of renaming the plugin, I'm not sure what the impacts are. I'm assuming it's a breaking change but are there any other impacts we'd need to consider?

**Comment by oliverfoster** [comment]
Impacts existing AATs where the plugin is installed and might need to be updated. This would be a replacement plugin, not an upgrade if renamed, which means all old courses using it would need to be reconfigured.

Perhaps do this when migrations stuff is ready and in.

**Comment by swashbuck** [comment]
Closing this issue as this will be more of a global effort for the future.
