### ISSUE TITLE
settings are quite confusing...

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-homeButton#6]
Maybe it's just me being a bit dim but I find the settings for this quite confusing - particularly the use of the `_isEnabled` setting within course.json and contentObjects.json

This maybe down to the examples given in example.json - where `_isEnabled` is set to `false` for both the course.json and contentObjects.json entries - which seems like quite an unusual use-case?

**Comment by kirsty-hames** [comment]
@moloko config and documentation have had a bit of tlc. Does this resolve your issue?

https://github.com/cgkineo/adapt-homeButton/blob/master/example.json

**Comment by moloko** [comment]
@kirsty-hames to me example.json seems to be documenting quite an usual use-case: having the 'home button' enabled on the main menu as a way of getting back to the 'start page'

**Comment by kirsty-hames** [comment]
Yes I'd agree actually. It would probably make more sense to use the back button to route to the 'start page'. I imagine that's what we mostly do on projects.  

Perhaps the following should be moved to adapt-backButton instead?
https://github.com/cgkineo/adapt-homeButton/blob/44ad3db4e13db6179a370b4132d7f431bfcf4bf4/example.json#L12

I'm not sure if there is a use-case for customising the route ID for homeButton? A submenu perhaps but I personally prefer to use the backButton.
